import java.awt.event.*;
/**
 * ButtonListener reacts to clicks on the sample button.
 * Main 'test' class for a simple JButton demonstration
 * Original from CSE 143, Sp03.
 * 
 * @author Hal Perkins
 * @version 4/17/03; mod 1/22/05, vo 
 */ 
public class ButtonListener implements ActionListener {
 
  /**
   * Respond to events generated by the button.
   * @param e the event created by the button when it was clicked.
   */
  public void actionPerformed( ActionEvent e ) {
    System.out.println( e.getActionCommand( ) );
  }
}